# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/tanks.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import proto.tanks_pb2


class TankServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Healthz(self, stream: 'grpclib.server.Stream[proto.tanks_pb2.HealthzRequest, proto.tanks_pb2.HealthzResponse]') -> None:
        pass

    @abc.abstractmethod
    async def StartGame(self, stream: 'grpclib.server.Stream[proto.tanks_pb2.StartGameReq, proto.tanks_pb2.GameResp]') -> None:
        pass

    @abc.abstractmethod
    async def RunCommands(self, stream: 'grpclib.server.Stream[proto.tanks_pb2.CommandsReq, proto.tanks_pb2.GameResp]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/tantks.TankService/Healthz': grpclib.const.Handler(
                self.Healthz,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.tanks_pb2.HealthzRequest,
                proto.tanks_pb2.HealthzResponse,
            ),
            '/tantks.TankService/StartGame': grpclib.const.Handler(
                self.StartGame,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.tanks_pb2.StartGameReq,
                proto.tanks_pb2.GameResp,
            ),
            '/tantks.TankService/RunCommands': grpclib.const.Handler(
                self.RunCommands,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.tanks_pb2.CommandsReq,
                proto.tanks_pb2.GameResp,
            ),
        }


class TankServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Healthz = grpclib.client.UnaryUnaryMethod(
            channel,
            '/tantks.TankService/Healthz',
            proto.tanks_pb2.HealthzRequest,
            proto.tanks_pb2.HealthzResponse,
        )
        self.StartGame = grpclib.client.UnaryUnaryMethod(
            channel,
            '/tantks.TankService/StartGame',
            proto.tanks_pb2.StartGameReq,
            proto.tanks_pb2.GameResp,
        )
        self.RunCommands = grpclib.client.UnaryUnaryMethod(
            channel,
            '/tantks.TankService/RunCommands',
            proto.tanks_pb2.CommandsReq,
            proto.tanks_pb2.GameResp,
        )
